### ISSUE TITLE
Docs for write custom collectors

### ISSUE THREAD

**Issue by reypm** [maximebf/php-debugbar#263]
I want to use PH Debug Bar in a framework built by the company were I work. I want to integrate this with that framework, is there any docs for write/create custom Collectors? If not any chance to add it to the docs?

**Comment by losttheplot** [comment]
I have a similar problem and could also do with some help if that's possible please (not strictly an 'issue' I know). I'm using mysql PDO in a new custom project but do not have enough OOP experience to understand the php-debugbar docs regarding collectors. I have included the following:
```
$debugbar = new StandardDebugBar();
$pdo = new TraceablePDO(new PDO('
    mysql:host='.Config::get('DB_HOST').';
    dbname='.Config::get('DB_NAME').';
    charset='.Config::get('DB_CHARSET'), 
    Config::get('DB_USER'), 
    Config::get('DB_PASS')
));
$debugbar->addCollector(new PDOCollector($pdo));
```
but am getting the following JS error: "PhpDebugBar.Widgets.SQLQueriesWidget is not a constructor". This is a great project that seems to cater well for those using established frameworks and plugins, but the docs do not seem to offer much help for those of us still honing our OOP kung-fu (which is why I'm building my project in the first place). Any help would be much appreciated e.g. is there an example anywhere on the interweb of how to add or configure a non-framework mysql PDO collector please, and then how to output it to a debugbar widget?

**Comment by reypm** [comment]
@losttheplot there is some docs [here][1] but I think there is not enough, any advice on this concern @maximebf ?

 [1]: http://phpdebugbar.com/docs/data-collectors.html#creating-collectors

**Comment by losttheplot** [comment]
Thanks, but even though I've been procedurally coding for decades, I am not able to understand these docs well enough to create a controller. I think I need what you need: a guide or example that is a bit clearer as to what file goes where. And that's the main problem, that the docs assume you know enough about OOP/MVC to know which bits of code go in which files in which directories. Oh well; I realise that this is not a help forum, so I guess I won't be able to use this great tool for debugging and optimising mysql calls :(

**Comment by maximebf** [comment]
Indeed the doc is a bit lacking. There are two parts to collectors: the Collector class and the frontend widgets. PHP DebugBar provides a set of widgets which you can use to present your data but you can also create your own.

You can find some info about widgets here: http://phpdebugbar.com/docs/javascript-bar.html#widgets
The code for the builtin ones is located here: https://github.com/maximebf/php-debugbar/blob/master/src/DebugBar/Resources/widgets.js

As the doc says, your collector class can implement the Renderable interface and define the getWidgets() method "which returns an array of key/value pairs where key are control names and values control options as defined in JavascriptRenderer::addControl($name, $options)" (http://phpdebugbar.com/docs/rendering.html#defining-controls).

The way you collect your data is really up to you. The only important thing to remember is that the data you want to transmit to the frontend (ie. to the widget => so formatted as required by the widget) must be returned by collect() method of your collector which will be called once at the end of the request.

You can look into existing collectors to get some examples: https://github.com/maximebf/php-debugbar/tree/master/src/DebugBar/DataCollector.

@losttheplot how do you include the debug bar assets on the frontend? Are you using the builtin renderHead() or are you doing it manually? If the latter, then you're missing some of them (namely, the files in src/DebugBar/Resources/widgets/sqlqueries)

**Comment by losttheplot** [comment]
Thanks @maximebf. My vendor dir is separate to my public dir, therefore I copied the assets into my public assets dir, copied the output of renderHead(), then hard-coded the asset calls with the appropriate replacement paths. You are quite correct that I missed /widgets/sqlqueries/ as it was not being called directly. Thanks for that.

What is confusing me most is that there are already a set of collector components inside a PDO dir; I'm just not sure how to use them for my non-framework mysql project. Am I calling them correctly (see my post above), or do I need to create a completely new collector class? Are these components redundant to me? As I said, I appreciate that this is not a help forum, but would be grateful nonetheless :)

**Comment by losttheplot** [comment]
@maximebf  I have now hard-coded the calls for the missing assets, so I am seeing the 'database' tab and am not getting any errors, thanks. The problem is that even if I make a PDO query immediately before "$debugbar = new StandardDebugBar();", the query is not showing in the debugbar (0 statements were executed). Any ideas please?

**Comment by maximebf** [comment]
I don't see anything wrong with the code you provided. Are you properly using the TraceablePDO instance ($pdo in your example) to make the queries?

**Comment by losttheplot** [comment]
Thank you for pointing me in the right direction @maximebf. Being new to PDO, as well as OOP and MVC (but I'm no php novice), I had not realised that 'new TraceablePDO( )' needed to wrap the project's primary PDO instance - I thought it was additional to it (crazy I know, but such is life when one is swamped with new concepts and terminology to learn). So in order to put your simple, static-page Quick Start example into the context of my new OOP/MVC project skeleton, I did the following (for brevity, only the relevant code is shown):

In the main config file (i.e. at the point the app is bootstrapped)...
```
use DebugBar\StandardDebugBar;

if (DEBUG) {
  $GLOBALS['debugbar'] = new StandardDebugBar();
  $GLOBALS['debugbarRenderer'] = $GLOBALS['debugbar']->getJavascriptRenderer();
}

```

In the main database connection class (i.e. where the PDO instance is created)...
```
use DebugBar\DataCollector\PDO\TraceablePDO;
use DebugBar\DataCollector\PDO\PDOCollector;

class DatabaseFactory
{
    private $database;
    public function getConnection() {
        global $debugbar;
        if (!$this->database) {
            try {
                $options = array(PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_OBJ, PDO::ATTR_ERRMODE => PDO::ERRMODE_WARNING);
                if (DEBUG) {
                    $this->database = new TraceablePDO(
                       new PDO(Config::get('DB_TYPE') . ':host=' . Config::get('DB_HOST') . ';dbname=' .
                       Config::get('DB_NAME') . ';port=' . Config::get('DB_PORT') . ';charset=' . Config::get('DB_CHARSET'), 
                       Config::get('DB_USER'), Config::get('DB_PASS'), $options)
                    );
                    $debugbar->addCollector(new PDOCollector($this->database));
                } else {
                    ...
            } else {
                ...

```

In the main view class (i.e. where the output to screen is prepared)...
```
    public function renderJade($filename, $data = null)
    {
        global $debugbarRenderer;
        if (DEBUG) {
            $debugbody = $debugbarRenderer->render();
            // note that I am manually referencing the assets
            $debughead = '<link rel="stylesheet" href="/assets/debugbar/vendor/highlightjs/styles/github.css"> ...

```
This works - Yay!

I've explained how I've done it for two reasons: (1) so that others new to PDO/OOP/MVC might learn from the hours that it took me to work it all out, and (2) so that if - as is probably the case - I have made a complete mess of the way I have scoped everything together, you might point out the error of my ways (please).

Bringing the thread back on track (sorry for hijacking it @raypm), I would say that I really appreciate you putting this project up for others to benefit from - you're very kind - but that if you are able to write the docs a bit more novice-friendly e.g. by better explaining how the various components might fit into a typical MVC project, not just a single page example, you might be able to help even more people with your wonderful debugbar :)     ...please don't think I am ungrateful.
