### ISSUE TITLE
1.16.3> PDO> now trace only query with parameters

### ISSUE THREAD

**Issue by h2lsoft** [maximebf/php-debugbar#458]
Hi, since a recet update, PDO collector trace only query with parameters not regular query.
How can I fix that ?

Thanks you

**Comment by n0x073** [comment]
Comparing v1.16.0 with v1.16.3: https://github.com/maximebf/php-debugbar/compare/v1.16.0...v1.16.3
There aren't pdo collector changes.

**Comment by h2lsoft** [comment]
I updated to v1.16.4 but I confirm PDO with method query is not traced in debugbar,
only queries with method prepare() and execute().

**Comment by n0x073** [comment]
`$x->query("SELECT 1+1");` works for me with v1.16.3 and v1.16.4.
Is it the correct PDO instance? (maybe real pdo class is used instead of TraceablePDO)

**Comment by h2lsoft** [comment]
thanks, we use this code :

```
class DB {
public function connect($driver='mysql', $host='localhost', $username='root', $password='', $database='', $port='',  $pdo_options=[])
	{
		$dsn = "{$driver}:host={$host};dbname={$database};port={$port}";
	
		$this->connection = new PDO($dsn, $username, $password, $pdo_options);
		$this->connection->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
		
		return $this->connection;
	}
}

$DBM = new DB();
$pdo = $DBM->connect($db_package['driver'], $db_package['host'], $db_package['username'], $db_package['password'], 
$db_package['database'], $db_package['port'], $db_package['pdo_options']);


$debugBarObject = new \DebugBar\StandardDebugBar();
$debugBarObject->addCollector(new \DebugBar\DataCollector\ConfigCollector($configs));
$pdo_collector = new \DebugBar\DataCollector\PDO\TraceablePDO($pdo);
$debugBarObject->addCollector(new \DebugBar\DataCollector\PDO\PDOCollector($pdo_collector ));
```

**Comment by n0x073** [comment]
Just tried your code: https://gist.github.com/n0x073/b686d60dcbe3fcfb97d37948d19fe0c8
Result:
![grafik](https://user-images.githubusercontent.com/72650981/101781550-404caf80-3af8-11eb-80ff-7127b5b44838.png)
`->query();` works
`->prepare()->execute();` prepare statement and execute works
`->prepare()->execute();` prepare statement with params and execute works
`->exec();` works

Is it possible you are use: `$pdor->query("...");` instead of `$pdo_collector->query("...");` ?

**Comment by h2lsoft** [comment]
Thank you ! It is ok now, pdo link must be public (it was private).
